web:
  build: .
  ports:
    - "80:8081"
  volumes:
    - .:/src
  links:
    - db
  environment:
    - NODE_ENV=local
  working_dir: /src
  command: forever --watch --watchIgnore '!{server/**/*.js}' server/server.js
db:
  image: mongo:3.0.2